[features]
seeds = false
skip-lint = false
[programs.localnet]
bundled_program = "HzJPfyiji8iDsZq3PqDqnaKRL9ZnjubzkpjHzxgoEuUN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/leo/.config/solana/id.json"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
